# Generated by Django 4.1.7 on 2023-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='photo')),
                ('desc', models.TextField()),
            ],
        ),
    ]
